### ISSUE TITLE
what's server does librtmp support?

### ISSUE THREAD

**Issue by w279805299** [ButterflyTV/LibRtmp-Client-for-Android#8] opened 2016-05-27 02:30 UTC
When I used wowza server,I got  a first frame and  then fast farward for a few second. Instand of Adobe Media Server,It could not play any more.The question is what's server does this sdk support?And how can I compile by myself?

**Comment by davidcassany** [comment] 2016-05-27 11:22
Hi, I think this is a question related to librtmp rather than this project. I have tested this project using Nginx rtmp module (so, compile nginx including the rtmp module [here](https://github.com/arut/nginx-rtmp-module)), and in the past I also used ffserver with librtmp (ffmpeg rtmp implementation is based on rtmp, as most of multimedia opensource frameworks).

**Comment by w279805299** [comment] 2016-05-28 03:14
I had compiled nginx-rtmp-module with  default configuration and tested it use ExoPlayer-with-RTMP-and-FLV-seek.I got first frame after 10 seconds. It was so slowly .

**Comment by mekya** [comment] 2016-05-28 14:38
I am sorry for the delay. I was in a businees trip. 

I think the problem is something else. To figure out we need to test the stream.

**Comment by mekya** [comment] 2016-12-03 09:04
Closing issue. Comment it if you have something to say.

**Closed by mekya** 2016-12-03 09:04 UTC
